//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpusMTService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class OpusMTServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OpusMTServiceSettings defaultInstance = ((OpusMTServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OpusMTServiceSettings())));
        
        public static OpusMTServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://object.pouta.csc.fi/OPUS-MT-models/")]
        public string ModelStorageUrl {
            get {
                return ((string)(this["ModelStorageUrl"]));
            }
            set {
                this["ModelStorageUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fiskmo/")]
        public string LocalFiskmoDir {
            get {
                return ((string)(this["LocalFiskmoDir"]));
            }
            set {
                this["LocalFiskmoDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8477")]
        public string MtServicePort {
            get {
                return ((string)(this["MtServicePort"]));
            }
            set {
                this["MtServicePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("customize.yml")]
        public string CustomizationBaseConfig {
            get {
                return ((string)(this["CustomizationBaseConfig"]));
            }
            set {
                this["CustomizationBaseConfig"] = value;
            }
        }
    }
}
