//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpusCatTranslationProvider {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class OpusCatTpSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OpusCatTpSettings defaultInstance = ((OpusCatTpSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OpusCatTpSettings())));
        
        public static OpusCatTpSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8477")]
        public string MtServicePort {
            get {
                return ((string)(this["MtServicePort"]));
            }
            set {
                this["MtServicePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SupportAllLanguagePairs {
            get {
                return ((bool)(this["SupportAllLanguagePairs"]));
            }
            set {
                this["SupportAllLanguagePairs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string MtServiceAddress {
            get {
                return ((string)(this["MtServiceAddress"]));
            }
            set {
                this["MtServiceAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int FinetuningSentencePairsHardLimit {
            get {
                return ((int)(this["FinetuningSentencePairsHardLimit"]));
            }
            set {
                this["FinetuningSentencePairsHardLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int FinetuningMaxSentencePairs {
            get {
                return ((int)(this["FinetuningMaxSentencePairs"]));
            }
            set {
                this["FinetuningMaxSentencePairs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FinetuningMaxFuzzyResults {
            get {
                return ((int)(this["FinetuningMaxFuzzyResults"]));
            }
            set {
                this["FinetuningMaxFuzzyResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int FinetuningMinFuzzyPercentage {
            get {
                return ((int)(this["FinetuningMinFuzzyPercentage"]));
            }
            set {
                this["FinetuningMinFuzzyPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int FinetuningMinSentencePairs {
            get {
                return ((int)(this["FinetuningMinSentencePairs"]));
            }
            set {
                this["FinetuningMinSentencePairs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FinetuningMaxConcordanceResults {
            get {
                return ((int)(this["FinetuningMaxConcordanceResults"]));
            }
            set {
                this["FinetuningMaxConcordanceResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxConcordanceWindow {
            get {
                return ((int)(this["MaxConcordanceWindow"]));
            }
            set {
                this["MaxConcordanceWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int PregenerateSegmentCount {
            get {
                return ((int)(this["PregenerateSegmentCount"]));
            }
            set {
                this["PregenerateSegmentCount"] = value;
            }
        }
    }
}
