//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpusCatMTEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpusCatMTEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database confirmation.
        /// </summary>
        public static string App_ConfirmDbCaption {
            get {
                return ResourceManager.GetString("App_ConfirmDbCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The existing translation database was created for an older version of OPUS-CAT MT Engine. A new database must be created for the new version. Delete old database and create a new one by clicking OK. If you click Cancel, the database will be kept, but the caching of translations into the database will disabled (it can be re-enabled in settings)..
        /// </summary>
        public static string App_InvalidDbMessage {
            get {
                return ResourceManager.GetString("App_InvalidDbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Finetune_BrowseButton {
            get {
                return ResourceManager.GetString("Finetune_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        public static string Finetune_FileDoesNotExistMessage {
            get {
                return ResourceManager.GetString("Finetune_FileDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine-tuned model label.
        /// </summary>
        public static string Finetune_FinetunedModelTagLabel {
            get {
                return ResourceManager.GetString("Finetune_FinetunedModelTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine-tune model {0}.
        /// </summary>
        public static string Finetune_FineTuneWindowTitle {
            get {
                return ResourceManager.GetString("Finetune_FineTuneWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Finetune_GenericValidationErrorMessage {
            get {
                return ResourceManager.GetString("Finetune_GenericValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include placeholder tags as text.
        /// </summary>
        public static string Finetune_IncludePlaceholderTagsCheckbox {
            get {
                return ResourceManager.GetString("Finetune_IncludePlaceholderTagsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include tag pairs as text.
        /// </summary>
        public static string Finetune_IncludeTagPairsCheckbox {
            get {
                return ResourceManager.GetString("Finetune_IncludeTagPairsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model tag is already in use for this base model.
        /// </summary>
        public static string Finetune_ModelTagInUseMessage {
            get {
                return ResourceManager.GetString("Finetune_ModelTagInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model tag not specified..
        /// </summary>
        public static string Finetune_ModelTagNotSpecifiedMessage {
            get {
                return ResourceManager.GetString("Finetune_ModelTagNotSpecifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model tag is too long..
        /// </summary>
        public static string Finetune_ModelTagTooLongMessage {
            get {
                return ResourceManager.GetString("Finetune_ModelTagTooLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough parallel segments in the TMX..
        /// </summary>
        public static string Finetune_NotEnoughSegmentsInTmx {
            get {
                return ResourceManager.GetString("Finetune_NotEnoughSegmentsInTmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select separate files.
        /// </summary>
        public static string Finetune_SeparateFilesRadioButton {
            get {
                return ResourceManager.GetString("Finetune_SeparateFilesRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file.
        /// </summary>
        public static string Finetune_SourceFileLabel {
            get {
                return ResourceManager.GetString("Finetune_SourceFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split validation files from the training files.
        /// </summary>
        public static string Finetune_SplitFromTrainingRadioButton {
            get {
                return ResourceManager.GetString("Finetune_SplitFromTrainingRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine-tune.
        /// </summary>
        public static string Finetune_StartFinetuneButton {
            get {
                return ResourceManager.GetString("Finetune_StartFinetuneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag processing.
        /// </summary>
        public static string Finetune_TagProcessingLabel {
            get {
                return ResourceManager.GetString("Finetune_TagProcessingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target file.
        /// </summary>
        public static string Finetune_TargetFileLabel {
            get {
                return ResourceManager.GetString("Finetune_TargetFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tmx file.
        /// </summary>
        public static string Finetune_TmxFileLabel {
            get {
                return ResourceManager.GetString("Finetune_TmxFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid .tmx file.
        /// </summary>
        public static string Finetune_TmxFileNotValidMessage {
            get {
                return ResourceManager.GetString("Finetune_TmxFileNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMX translation memory.
        /// </summary>
        public static string Finetune_TmxRadioButton {
            get {
                return ResourceManager.GetString("Finetune_TmxRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training files.
        /// </summary>
        public static string Finetune_TrainingFilesLabel {
            get {
                return ResourceManager.GetString("Finetune_TrainingFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text (separate files for source and target).
        /// </summary>
        public static string Finetune_TxtFilesRadioButton {
            get {
                return ResourceManager.GetString("Finetune_TxtFilesRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation files (for monitoring the progress of training).
        /// </summary>
        public static string Finetune_ValidationFilesLabel {
            get {
                return ResourceManager.GetString("Finetune_ValidationFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation source file.
        /// </summary>
        public static string Finetune_ValidationSourceFileLabel {
            get {
                return ResourceManager.GetString("Finetune_ValidationSourceFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation target file.
        /// </summary>
        public static string Finetune_ValidationTargetFileLabel {
            get {
                return ResourceManager.GetString("Finetune_ValidationTargetFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel override.
        /// </summary>
        public static string Main_CancelOverrideButton {
            get {
                return ResourceManager.GetString("Main_CancelOverrideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        public static string Main_ConfirmExitCaption {
            get {
                return ResourceManager.GetString("Main_ConfirmExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine-tuning or batch translation is in progress. Fine-tuning can be resumed later from the last save point, but batch translation will be aborted permanently. Are you sure you want to close the OpusCAT MT Engine?.
        /// </summary>
        public static string Main_ConfirmExitMessage {
            get {
                return ResourceManager.GetString("Main_ConfirmExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue fine-tuning.
        /// </summary>
        public static string Main_ContinueFinetuneButton {
            get {
                return ResourceManager.GetString("Main_ContinueFinetuneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fine-tuning progress.
        /// </summary>
        public static string Main_CustomizationProgressButton {
            get {
                return ResourceManager.GetString("Main_CustomizationProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected model.
        /// </summary>
        public static string Main_DeleteModelButton {
            get {
                return ResourceManager.GetString("Main_DeleteModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete model {0}? Deletion is permanent..
        /// </summary>
        public static string Main_DeleteModelConfirmation {
            get {
                return ResourceManager.GetString("Main_DeleteModelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string Main_DeleteModelConfirmationTitle {
            get {
                return ResourceManager.GetString("Main_DeleteModelConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit model tags.
        /// </summary>
        public static string Main_EditModelTagsButton {
            get {
                return ResourceManager.GetString("Main_EditModelTagsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine-tune selected model.
        /// </summary>
        public static string Main_FinetuneButton {
            get {
                return ResourceManager.GetString("Main_FinetuneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install OPUS model from Web.
        /// </summary>
        public static string Main_InstallFromWebButton {
            get {
                return ResourceManager.GetString("Main_InstallFromWebButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install model from zip.
        /// </summary>
        public static string Main_InstallFromZipButton {
            get {
                return ResourceManager.GetString("Main_InstallFromZipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Main_ModelsTabTitle {
            get {
                return ResourceManager.GetString("Main_ModelsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal characters in path.
        /// </summary>
        public static string Main_NonAsciiPathCaption {
            get {
                return ResourceManager.GetString("Main_NonAsciiPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where OPUS-CAT MT Engine stores MT models ({0}) contains the following illegal characters: {1}. Install OPUS-CAT MT Engine to a path with no illegal characters in it (for instance, in a folder in the root of the C: drive, such as C:\opuscat)..
        /// </summary>
        public static string Main_NonAsciiPathMessage {
            get {
                return ResourceManager.GetString("Main_NonAsciiPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online models.
        /// </summary>
        public static string Main_OnlineModelsTab {
            get {
                return ResourceManager.GetString("Main_OnlineModelsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model directory.
        /// </summary>
        public static string Main_OpenModelDirButton {
            get {
                return ResourceManager.GetString("Main_OpenModelDirButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPUS-CAT MT Engine v{0}.
        /// </summary>
        public static string Main_OpusCatWindowTitle {
            get {
                return ResourceManager.GetString("Main_OpusCatWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package fine-tuned model.
        /// </summary>
        public static string Main_PackageModelButton {
            get {
                return ResourceManager.GetString("Main_PackageModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as override model.
        /// </summary>
        public static string Main_SetAsOverrideModelButton {
            get {
                return ResourceManager.GetString("Main_SetAsOverrideModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Main_SettingsTabTitle {
            get {
                return ResourceManager.GetString("Main_SettingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate with model.
        /// </summary>
        public static string Main_TranslateWithModelButton {
            get {
                return ResourceManager.GetString("Main_TranslateWithModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Online_DownloadingStatus {
            get {
                return ResourceManager.GetString("Online_DownloadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        public static string Online_ExtractingStatus {
            get {
                return ResourceManager.GetString("Online_ExtractingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation progress.
        /// </summary>
        public static string Online_InstallationProgressHeader {
            get {
                return ResourceManager.GetString("Online_InstallationProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Online_InstalledStatus {
            get {
                return ResourceManager.GetString("Online_InstalledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install model locally.
        /// </summary>
        public static string Online_InstallModelLocallyButton {
            get {
                return ResourceManager.GetString("Online_InstallModelLocallyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name filter.
        /// </summary>
        public static string Online_ModelNameFilterLabel {
            get {
                return ResourceManager.GetString("Online_ModelNameFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name.
        /// </summary>
        public static string Online_ModelNameHeader {
            get {
                return ResourceManager.GetString("Online_ModelNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model origin.
        /// </summary>
        public static string Online_ModelOriginHeader {
            get {
                return ResourceManager.GetString("Online_ModelOriginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source filter.
        /// </summary>
        public static string Online_SourceLangFilterLabel {
            get {
                return ResourceManager.GetString("Online_SourceLangFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source languages.
        /// </summary>
        public static string Online_SourceLanguagesHeader {
            get {
                return ResourceManager.GetString("Online_SourceLanguagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target filter.
        /// </summary>
        public static string Online_TargetLangFilterLabel {
            get {
                return ResourceManager.GetString("Online_TargetLangFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target languages.
        /// </summary>
        public static string Online_TargetLanguagesHeader {
            get {
                return ResourceManager.GetString("Online_TargetLanguagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model as overlay.
        /// </summary>
        public static string OpenModelInOverlayButton {
            get {
                return ResourceManager.GetString("OpenModelInOverlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap opus {
            get {
                object obj = ResourceManager.GetObject("opus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLEU score.
        /// </summary>
        public static string Progress_BleuAxis {
            get {
                return ResourceManager.GetString("Progress_BleuAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-domain validation set.
        /// </summary>
        public static string Progress_InDomainSeriesName {
            get {
                return ResourceManager.GetString("Progress_InDomainSeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out-of-domain validation set.
        /// </summary>
        public static string Progress_OutOfDomainSeriesName {
            get {
                return ResourceManager.GetString("Progress_OutOfDomainSeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation step.
        /// </summary>
        public static string Progress_ValidationStepAxis {
            get {
                return ResourceManager.GetString("Progress_ValidationStepAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TMX file does not contain languages compatible with the language codes of the MT model, or there are not enough segments for the compatible language pair. Language pairs included in the TMX file and the amount of segments per language pair are listed below. You can either select one of the language pairs to extract as fine-tuning material, or cancel fine-tuning..
        /// </summary>
        public static string SelectTmxLangPair_Instructions {
            get {
                return ResourceManager.GetString("SelectTmxLangPair_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language pair.
        /// </summary>
        public static string SelectTmxLangPair_Title {
            get {
                return ResourceManager.GetString("SelectTmxLangPair_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port that OPUS-CAT MT Engine uses ({0}) is not available. Another instance of OPUS-CAT MT Engine may be active and using the port..
        /// </summary>
        public static string Service_PortNotAvailable {
            get {
                return ResourceManager.GetString("Service_PortNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT service HTTP port (used with current plugins and integrations, 1024-65535):.
        /// </summary>
        public static string Settings_HttpPortLabel {
            get {
                return ResourceManager.GetString("Settings_HttpPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT service net.tcp port (used with older Trados and memoQ plugins, 1024-65535):.
        /// </summary>
        public static string Settings_NetTcpPortLabel {
            get {
                return ResourceManager.GetString("Settings_NetTcpPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Settings_NoteHeading {
            get {
                return ResourceManager.GetString("Settings_NoteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open finetune settings in text editor.
        /// </summary>
        public static string Settings_OpenSettingsFileButton {
            get {
                return ResourceManager.GetString("Settings_OpenSettingsFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart OPUS-CAT MT Engine after changing these values..
        /// </summary>
        public static string Settings_RestartReminder {
            get {
                return ResourceManager.GetString("Settings_RestartReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to defaults.
        /// </summary>
        public static string Settings_RevertToDefaultsButton {
            get {
                return ResourceManager.GetString("Settings_RevertToDefaultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Settings_SaveButton {
            get {
                return ResourceManager.GetString("Settings_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store OPUS-CAT MT Engine data in local application data folder (instead of installation folder).
        /// </summary>
        public static string Settings_StoreInAppdataCheckbox {
            get {
                return ResourceManager.GetString("Settings_StoreInAppdataCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Tags_AddTagButton {
            get {
                return ResourceManager.GetString("Tags_AddTagButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Tags_DeleteTagButton {
            get {
                return ResourceManager.GetString("Tags_DeleteTagButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tags for {0}.
        /// </summary>
        public static string Tags_EditTagsTitle {
            get {
                return ResourceManager.GetString("Tags_EditTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model tags.
        /// </summary>
        public static string Tags_ModelTagsLabel {
            get {
                return ResourceManager.GetString("Tags_ModelTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source text:.
        /// </summary>
        public static string Translate_SourceTextLabel {
            get {
                return ResourceManager.GetString("Translate_SourceTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate_TranslateButton {
            get {
                return ResourceManager.GetString("Translate_TranslateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating with model {0}.
        /// </summary>
        public static string Translate_TranslateTitle {
            get {
                return ResourceManager.GetString("Translate_TranslateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation:.
        /// </summary>
        public static string Translate_TranslationLabel {
            get {
                return ResourceManager.GetString("Translate_TranslationLabel", resourceCulture);
            }
        }
    }
}
